// Real summit-attendee data for the WorldGlobeSummit visualization, sourced
// from summit-attendees.csv (one row per attendee: organization, member
// status, country, city).

export interface SummitAttendee {
  id: number;
  agency: string;
  iso2: string;
  municipality: string;
  isMember: boolean;
}

export interface SummitCity {
  municipality: string;
  iso2: string;
  lat: number;
  lon: number;
}

// Approximate city-center coordinates for each attendee's home
// municipality, used to place a marker dot on the globe. Keyed by
// municipality name rather than agency, since a city can host more than one
// agency (e.g. Montreal) and should still get a single dot.
const MUNICIPALITY_COORDS: Record<string, { lat: number; lon: number }> = {
  Bucharest: { lat: 44.4268, lon: 26.1025 },
  Paris: { lat: 48.8566, lon: 2.3522 },
  'Washington, D.C.': { lat: 38.9072, lon: -77.0369 },
  Kathmandu: { lat: 27.7172, lon: 85.324 },
  Chicago: { lat: 41.8781, lon: -87.6298 },
  Tokyo: { lat: 35.6762, lon: 139.6503 },
  'Belo Horizonte': { lat: -19.9167, lon: -43.9345 },
  Melbourne: { lat: -37.8136, lon: 144.9631 },
  Montreal: { lat: 45.5017, lon: -73.5673 },
  Hamburg: { lat: 53.5511, lon: 9.9937 },
  Cambridge: { lat: 52.2053, lon: 0.1218 },
  Boston: { lat: 42.3601, lon: -71.0589 },
  Copenhagen: { lat: 55.6761, lon: 12.5683 },
  Oslo: { lat: 59.9139, lon: 10.7522 },
  'San Francisco': { lat: 37.7749, lon: -122.4194 },
  Barcelona: { lat: 41.3851, lon: 2.1734 },
  Brussels: { lat: 50.8503, lon: 4.3517 },
  Cairo: { lat: 30.0444, lon: 31.2357 },
  Toronto: { lat: 43.6532, lon: -79.3832 },
  'Los Angeles': { lat: 34.0522, lon: -118.2437 },
  Rockville: { lat: 39.084, lon: -77.1528 },
  Seattle: { lat: 47.6062, lon: -122.3321 },
  Philadelphia: { lat: 39.9526, lon: -75.1652 },
  'New York': { lat: 40.7128, lon: -74.006 },
  Calgary: { lat: 51.0447, lon: -114.0719 },
  'San Juan': { lat: 18.4655, lon: -66.1057 },
  Lansing: { lat: 42.7325, lon: -84.5555 },
  London: { lat: 51.5074, lon: -0.1278 },
  Portland: { lat: 45.5152, lon: -122.6784 },
  Providence: { lat: 41.824, lon: -71.4128 },
  Cupertino: { lat: 37.323, lon: -122.0322 },
  'Mexico City': { lat: 19.4326, lon: -99.1332 },
  Sacramento: { lat: 38.5816, lon: -121.4944 },
  Wellington: { lat: -41.2865, lon: 174.7762 },
  Bangalore: { lat: 12.9716, lon: 77.5946 },
  'San Jose': { lat: 37.3382, lon: -121.8863 },
  Ottawa: { lat: 45.4215, lon: -75.6972 },
  Burnaby: { lat: 49.2488, lon: -122.9805 },
  'Santa Clara': { lat: 37.3541, lon: -121.9552 },
  'Kansas City': { lat: 39.0997, lon: -94.5786 },
  Osaka: { lat: 34.6937, lon: 135.5023 },
  'Boca Raton': { lat: 26.3683, lon: -80.1289 },
  Woburn: { lat: 42.4793, lon: -71.1523 },
  Minneapolis: { lat: 44.9778, lon: -93.265 },
  'Cedar Rapids': { lat: 41.9779, lon: -91.6656 },
  Miami: { lat: 25.7617, lon: -80.1918 },
  Burlington: { lat: 44.4759, lon: -73.2121 },
  'Mountain View': { lat: 37.3861, lon: -122.0839 },
  Mississauga: { lat: 43.589, lon: -79.6441 },
};

// Attendee list generated from summit-attendees.csv.
export const SUMMIT_ATTENDEES: SummitAttendee[] = [
  {
    id: 0,
    agency: 'FlashWeb IT',
    iso2: 'RO',
    municipality: 'Bucharest',
    isMember: true,
  },
  {
    id: 1,
    agency: 'enRoute',
    iso2: 'FR',
    municipality: 'Paris',
    isMember: true,
  },
  {
    id: 2,
    agency: 'ITS America',
    iso2: 'US',
    municipality: 'Washington, D.C.',
    isMember: false,
  },
  {
    id: 3,
    agency: 'Rural Area Development Programme (RADP)',
    iso2: 'NP',
    municipality: 'Kathmandu',
    isMember: false,
  },
  {
    id: 4,
    agency: 'Rural Area Development Programme (RADP)',
    iso2: 'NP',
    municipality: 'Kathmandu',
    isMember: false,
  },
  {
    id: 5,
    agency: 'Shared-Use Mobility Center',
    iso2: 'US',
    municipality: 'Chicago',
    isMember: false,
  },
  {
    id: 6,
    agency: 'Val Laboratory Corporation',
    iso2: 'JP',
    municipality: 'Tokyo',
    isMember: false,
  },
  {
    id: 7,
    agency: 'Val Laboratory Corporation',
    iso2: 'JP',
    municipality: 'Tokyo',
    isMember: false,
  },
  {
    id: 8,
    agency: 'Bus2',
    iso2: 'BR',
    municipality: 'Belo Horizonte',
    isMember: true,
  },
  {
    id: 9,
    agency: 'transport.data.gouv — France NAP',
    iso2: 'FR',
    municipality: 'Paris',
    isMember: true,
  },
  {
    id: 10,
    agency: 'Rome2rio (Omio)',
    iso2: 'AU',
    municipality: 'Melbourne',
    isMember: false,
  },
  { id: 11, agency: 'ODPT', iso2: 'JP', municipality: 'Tokyo', isMember: true },
  {
    id: 12,
    agency: 'ARTM — Montreal area',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: true,
  },
  {
    id: 13,
    agency: 'Agence de Mobilité Durable Montréal',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: true,
  },
  {
    id: 14,
    agency: 'HVV — Hamburg',
    iso2: 'DE',
    municipality: 'Hamburg',
    isMember: true,
  },
  {
    id: 15,
    agency: 'Ito World',
    iso2: 'GB',
    municipality: 'Cambridge',
    isMember: true,
  },
  {
    id: 16,
    agency: 'Transit App',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: true,
  },
  {
    id: 17,
    agency: 'Kuban Transit Solutions',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: false,
  },
  {
    id: 18,
    agency: 'MBTA',
    iso2: 'US',
    municipality: 'Boston',
    isMember: true,
  },
  {
    id: 19,
    agency: 'Metroselskabet — Copenhagen',
    iso2: 'DK',
    municipality: 'Copenhagen',
    isMember: false,
  },
  {
    id: 20,
    agency: 'Entur — Norway',
    iso2: 'NO',
    municipality: 'Oslo',
    isMember: true,
  },
  {
    id: 21,
    agency: 'Swiftly',
    iso2: 'US',
    municipality: 'San Francisco',
    isMember: true,
  },
  {
    id: 22,
    agency: 'Agence de Mobilité Durable Montréal',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: true,
  },
  {
    id: 23,
    agency:
      'Tècnic del Centre de Gestió de la Informació de la Mobilitat (CGIM)',
    iso2: 'ES',
    municipality: 'Barcelona',
    isMember: false,
  },
  {
    id: 24,
    agency: 'MTC',
    iso2: 'US',
    municipality: 'San Francisco',
    isMember: true,
  },
  {
    id: 25,
    agency: 'Polis Network',
    iso2: 'BE',
    municipality: 'Brussels',
    isMember: true,
  },
  {
    id: 26,
    agency: 'Transit',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: true,
  },
  {
    id: 27,
    agency: 'Transit',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: true,
  },
  {
    id: 28,
    agency: 'Université de Montréal',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: false,
  },
  {
    id: 29,
    agency: 'Transit',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: true,
  },
  {
    id: 30,
    agency: 'Transport for Cairo',
    iso2: 'EG',
    municipality: 'Cairo',
    isMember: false,
  },
  {
    id: 31,
    agency: 'HVV GmbH',
    iso2: 'DE',
    municipality: 'Hamburg',
    isMember: true,
  },
  {
    id: 32,
    agency: 'Massachusetts Bay Transportation Authority',
    iso2: 'US',
    municipality: 'Boston',
    isMember: true,
  },
  {
    id: 33,
    agency: 'CSA Group',
    iso2: 'CA',
    municipality: 'Toronto',
    isMember: false,
  },
  {
    id: 34,
    agency: 'LA Metro',
    iso2: 'US',
    municipality: 'Los Angeles',
    isMember: false,
  },
  {
    id: 35,
    agency: 'City of Montréal',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: false,
  },
  {
    id: 36,
    agency: 'GMV',
    iso2: 'US',
    municipality: 'Rockville',
    isMember: false,
  },
  {
    id: 37,
    agency:
      'Federal Transit Administration (U.S. Department of Transportation)',
    iso2: 'US',
    municipality: 'Washington, D.C.',
    isMember: false,
  },
  {
    id: 38,
    agency: 'Bus2',
    iso2: 'BR',
    municipality: 'Belo Horizonte',
    isMember: true,
  },
  {
    id: 39,
    agency: 'King County Metro',
    iso2: 'US',
    municipality: 'Seattle',
    isMember: true,
  },
  {
    id: 40,
    agency: 'Jarvus Innovations',
    iso2: 'US',
    municipality: 'Philadelphia',
    isMember: false,
  },
  {
    id: 41,
    agency: 'Toyota Mobility Foundation',
    iso2: 'US',
    municipality: 'Washington, D.C.',
    isMember: false,
  },
  {
    id: 42,
    agency: 'Beta Mobility',
    iso2: 'NO',
    municipality: 'Oslo',
    isMember: false,
  },
  {
    id: 43,
    agency: 'Siemens Mobilty',
    iso2: 'US',
    municipality: 'New York',
    isMember: false,
  },
  {
    id: 44,
    agency: 'Transit App',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: true,
  },
  {
    id: 45,
    agency: 'Transit App',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: true,
  },
  {
    id: 46,
    agency: 'Interline Technologies',
    iso2: 'US',
    municipality: 'San Francisco',
    isMember: false,
  },
  {
    id: 47,
    agency: 'Klumpentown Consulting',
    iso2: 'CA',
    municipality: 'Calgary',
    isMember: false,
  },
  {
    id: 48,
    agency: 'DVS & Asociados, LLC',
    iso2: 'PR',
    municipality: 'San Juan',
    isMember: true,
  },
  {
    id: 49,
    agency: 'Michigan Department of Transportation',
    iso2: 'US',
    municipality: 'Lansing',
    isMember: false,
  },
  {
    id: 50,
    agency: 'Polytechnique Montreal - Chaire Moblité',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: true,
  },
  {
    id: 51,
    agency: 'Lime',
    iso2: 'US',
    municipality: 'San Francisco',
    isMember: false,
  },
  {
    id: 52,
    agency: 'ITES Media',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: true,
  },
  {
    id: 53,
    agency: 'ITES Media',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: true,
  },
  {
    id: 54,
    agency: 'Chicago Transit Authority',
    iso2: 'US',
    municipality: 'Chicago',
    isMember: false,
  },
  {
    id: 55,
    agency: 'STM',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: true,
  },
  {
    id: 56,
    agency: 'Masabi',
    iso2: 'GB',
    municipality: 'London',
    isMember: false,
  },
  {
    id: 57,
    agency: 'Full Path LLC',
    iso2: 'US',
    municipality: 'Portland',
    isMember: true,
  },
  {
    id: 58,
    agency: 'Jarvus Innovations',
    iso2: 'US',
    municipality: 'Philadelphia',
    isMember: false,
  },
  {
    id: 59,
    agency: 'Swiftly',
    iso2: 'US',
    municipality: 'San Francisco',
    isMember: true,
  },
  {
    id: 60,
    agency: 'Rhode Island Public Transit Authority',
    iso2: 'US',
    municipality: 'Providence',
    isMember: false,
  },
  {
    id: 61,
    agency: 'Rhode Island Public Transit Authority',
    iso2: 'US',
    municipality: 'Providence',
    isMember: false,
  },
  {
    id: 62,
    agency: 'Apple Inc',
    iso2: 'US',
    municipality: 'Cupertino',
    isMember: true,
  },
  {
    id: 63,
    agency: 'Transamo',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: false,
  },
  {
    id: 64,
    agency: 'Arup',
    iso2: 'US',
    municipality: 'New York',
    isMember: false,
  },
  {
    id: 65,
    agency: 'Codeando México',
    iso2: 'MX',
    municipality: 'Mexico City',
    isMember: true,
  },
  {
    id: 66,
    agency: 'Actionfigure',
    iso2: 'US',
    municipality: 'Washington, D.C.',
    isMember: true,
  },
  {
    id: 67,
    agency: 'Axon Vibe',
    iso2: 'US',
    municipality: 'New York',
    isMember: false,
  },
  {
    id: 68,
    agency: 'California Integrated Travel Project (Cal-ITP)',
    iso2: 'US',
    municipality: 'Sacramento',
    isMember: false,
  },
  {
    id: 69,
    agency: 'Snapper Services',
    iso2: 'NZ',
    municipality: 'Wellington',
    isMember: true,
  },
  {
    id: 70,
    agency: 'Centre of Data for Public Good, Indian Institute of Science',
    iso2: 'IN',
    municipality: 'Bangalore',
    isMember: false,
  },
  {
    id: 71,
    agency: 'Santa Clara Valley Transportation Authority',
    iso2: 'US',
    municipality: 'San Jose',
    isMember: false,
  },
  {
    id: 72,
    agency: 'Statistics Canada',
    iso2: 'CA',
    municipality: 'Ottawa',
    isMember: false,
  },
  {
    id: 73,
    agency: 'Polytechnique montreal',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: true,
  },
  {
    id: 74,
    agency: 'BCAA',
    iso2: 'CA',
    municipality: 'Burnaby',
    isMember: true,
  },
  {
    id: 75,
    agency: 'Agence de Mobilité durable',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: true,
  },
  {
    id: 76,
    agency: 'Hitachi',
    iso2: 'US',
    municipality: 'Santa Clara',
    isMember: true,
  },
  {
    id: 77,
    agency: 'HNTB',
    iso2: 'US',
    municipality: 'Kansas City',
    isMember: false,
  },
  {
    id: 78,
    agency: 'Arup',
    iso2: 'US',
    municipality: 'New York',
    isMember: false,
  },
  {
    id: 79,
    agency: 'TransitOPS',
    iso2: 'US',
    municipality: 'Los Angeles',
    isMember: false,
  },
  {
    id: 80,
    agency: 'WMATA',
    iso2: 'US',
    municipality: 'Washington, D.C.',
    isMember: true,
  },
  {
    id: 81,
    agency: 'Metropolitan Transportation Authority',
    iso2: 'US',
    municipality: 'New York',
    isMember: false,
  },
  {
    id: 82,
    agency: 'WILLER, Inc.',
    iso2: 'JP',
    municipality: 'Osaka',
    isMember: false,
  },
  {
    id: 83,
    agency: 'ETA Transit',
    iso2: 'US',
    municipality: 'Boca Raton',
    isMember: false,
  },
  {
    id: 84,
    agency: 'National Rural Transit Assistance Program',
    iso2: 'US',
    municipality: 'Woburn',
    isMember: false,
  },
  {
    id: 85,
    agency: 'WMATA',
    iso2: 'US',
    municipality: 'Washington, D.C.',
    isMember: false,
  },
  {
    id: 86,
    agency: 'Consystec',
    iso2: 'US',
    municipality: 'Washington, D.C.',
    isMember: false,
  },
  {
    id: 87,
    agency: 'Metro Transit (St. Paul/Minneapolis, MN)',
    iso2: 'US',
    municipality: 'Minneapolis',
    isMember: true,
  },
  {
    id: 88,
    agency: 'Trapeze Software',
    iso2: 'US',
    municipality: 'Cedar Rapids',
    isMember: false,
  },
  { id: 89, agency: 'Entur', iso2: 'NO', municipality: 'Oslo', isMember: true },
  {
    id: 90,
    agency:
      'Support for National Rural Transit Assistance Program (USA)/Transnnovation Inc',
    iso2: 'US',
    municipality: 'Woburn',
    isMember: false,
  },
  {
    id: 91,
    agency: 'FIFA World Cup 2026',
    iso2: 'US',
    municipality: 'Miami',
    isMember: false,
  },
  {
    id: 92,
    agency: 'Caltrans',
    iso2: 'US',
    municipality: 'Sacramento',
    isMember: false,
  },
  {
    id: 93,
    agency: 'Caltrans',
    iso2: 'US',
    municipality: 'Sacramento',
    isMember: false,
  },
  {
    id: 94,
    agency: 'Caltrans',
    iso2: 'US',
    municipality: 'Sacramento',
    isMember: false,
  },
  {
    id: 95,
    agency: 'strada360',
    iso2: 'CA',
    municipality: 'Toronto',
    isMember: false,
  },
  {
    id: 96,
    agency: 'Green Mountain Transit',
    iso2: 'US',
    municipality: 'Burlington',
    isMember: false,
  },
  {
    id: 97,
    agency: 'Google',
    iso2: 'US',
    municipality: 'Mountain View',
    isMember: true,
  },
  {
    id: 98,
    agency: 'TripSpark Technologies',
    iso2: 'CA',
    municipality: 'Mississauga',
    isMember: false,
  },
  {
    id: 99,
    agency: 'Réseau de transport Métropolitain',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: true,
  },
  {
    id: 100,
    agency: 'Réseau de transport Métropolitain',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: true,
  },
  {
    id: 101,
    agency: 'Google',
    iso2: 'US',
    municipality: 'Mountain View',
    isMember: true,
  },
  {
    id: 102,
    agency: 'Google',
    iso2: 'US',
    municipality: 'Mountain View',
    isMember: true,
  },
  {
    id: 103,
    agency: 'Google',
    iso2: 'US',
    municipality: 'Mountain View',
    isMember: true,
  },
  {
    id: 104,
    agency: 'The Government Accountability Office',
    iso2: 'US',
    municipality: 'Washington, D.C.',
    isMember: false,
  },
  {
    id: 105,
    agency: 'The Government Accountability Office',
    iso2: 'US',
    municipality: 'Washington, D.C.',
    isMember: false,
  },
  {
    id: 106,
    agency: 'Frontera',
    iso2: 'US',
    municipality: 'Washington, D.C.',
    isMember: false,
  },
  {
    id: 107,
    agency: 'National RTAP',
    iso2: 'US',
    municipality: 'Woburn',
    isMember: false,
  },
  {
    id: 108,
    agency: 'Apple Inc',
    iso2: 'US',
    municipality: 'Cupertino',
    isMember: true,
  },
  {
    id: 109,
    agency: 'Sound Transit',
    iso2: 'US',
    municipality: 'Seattle',
    isMember: true,
  },
  {
    id: 110,
    agency: 'Apple',
    iso2: 'US',
    municipality: 'Cupertino',
    isMember: true,
  },
  {
    id: 111,
    agency: 'Lyft Urban Solutions',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: false,
  },
  {
    id: 112,
    agency: 'Via Transportation',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: false,
  },
  {
    id: 113,
    agency: 'STM',
    iso2: 'CA',
    municipality: 'Montreal',
    isMember: true,
  },
];

// One entry per unique municipality (not per agency) for the globe's
// pulsating city markers.
export const SUMMIT_CITIES: SummitCity[] = Array.from(
  new Map(
    SUMMIT_ATTENDEES.map((a) => [
      a.municipality,
      {
        municipality: a.municipality,
        iso2: a.iso2,
        ...MUNICIPALITY_COORDS[a.municipality],
      },
    ]),
  ).values(),
);

// ISO2 -> attendees, for fast lookup on country click.
export const ATTENDEES_BY_COUNTRY: Record<string, SummitAttendee[]> =
  SUMMIT_ATTENDEES.reduce<Record<string, SummitAttendee[]>>((acc, a) => {
    (acc[a.iso2] ??= []).push(a);
    return acc;
  }, {});

// Set of countries that have at least one attendee (drives map shading).
export const SUMMIT_COUNTRIES: Set<string> = new Set(
  Object.keys(ATTENDEES_BY_COUNTRY),
);
