/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/user': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get the current user's profile
     * @description Returns the authenticated user's profile. If no profile exists yet, one is created automatically
     *     (upsert on first call).
     */
    get: operations['getUser'];
    /**
     * Update the current user's profile
     * @description Updates the authenticated user's profile fields. Email cannot be changed here (requires
     *     re-verification).
     */
    put: operations['updateUser'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/notifications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List available notification types
     * @description Returns all predefined notification types that users can subscribe to.
     */
    get: operations['getNotifications'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/user/subscriptions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List the current user's notification subscriptions
     * @description Returns all notification subscriptions for the authenticated user.
     */
    get: operations['getUserSubscriptions'];
    put?: never;
    /**
     * Create a notification subscription
     * @description Subscribes the authenticated user to a notification type.
     */
    post: operations['createUserSubscription'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/user/subscriptions/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete a notification subscription
     * @description Removes a notification subscription by ID.
     */
    delete: operations['deleteUserSubscription'];
    options?: never;
    head?: never;
    /**
     * Toggle a notification subscription
     * @description Activates or deactivates a notification subscription by ID.
     */
    patch: operations['updateUserSubscription'];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    UserProfile: {
      /**
       * @description The user's unique identifier.
       * @example abc123uid
       */
      id: string;
      /**
       * Format: email
       * @description The user's email address. Read-only — cannot be changed via this API.
       * @example user@example.com
       */
      email?: string;
      /**
       * @description The user's full name.
       * @example Jane Doe
       */
      full_name?: string | null;
      /**
       * @deprecated
       * @description The user's legacy organisation name (migrated from the previous system). Deprecated: will be removed in a future version.
       * @example Acme Transit
       */
      legacy_org_name?: string | null;
      /** @description Whether the user's email address has been verified. */
      email_verified?: boolean | null;
      /**
       * @description Whether the user has opted in to receive API announcement emails.
       * @default false
       */
      is_registered_to_receive_api_announcements: boolean;
      /**
       * Format: date-time
       * @description Timestamp when the user record was created.
       */
      created_at?: string;
      /**
       * Format: date-time
       * @description Timestamp when the user record was last updated.
       */
      updated_at?: string;
    };
    /**
     * @description Fields to update on the user's profile. Only provided fields are updated (partial update).
     *     Email cannot be changed here.
     */
    UpdateUserRequest: {
      /**
       * @description The user's full name.
       * @example Jane Doe
       */
      full_name?: string | null;
      /**
       * @deprecated
       * @description The user's legacy organisation name (migrated from the previous system). Deprecated: will be removed in a future version.
       * @example Acme Transit
       */
      legacy_org_name?: string | null;
      /** @description Whether the user has opted in to receive API announcement emails. */
      is_registered_to_receive_api_announcements?: boolean;
    };
    NotificationType: {
      /**
       * @description Unique identifier for the notification type (e.g. 'feed.published').
       * @example feed.published
       */
      id: string;
      /**
       * @description Human-readable description of the notification type.
       * @example Notifies when a new feed is published.
       */
      description?: string | null;
    };
    NotificationSubscription: {
      /** @description Unique subscription ID (UUID v4). */
      id: string;
      /** @description The ID of the subscribed user. */
      user_id: string;
      /**
       * @description The notification type this subscription is for.
       * @example feed.published
       */
      notification_id: string;
      /**
       * @description Whether the subscription is currently active.
       * @default true
       */
      active: boolean;
      /**
       * Format: date-time
       * @description Timestamp of the last notification sent for this subscription.
       */
      last_notified_at?: string | null;
      /**
       * Format: date-time
       * @description Timestamp when the subscription was created.
       */
      created_at: string;
    };
    CreateNotificationSubscriptionRequest: {
      /**
       * @description The notification type to subscribe to.
       * @example feed.published
       */
      notification_id: string;
    };
    UpdateNotificationSubscriptionRequest: {
      /** @description Whether the subscription should be active. */
      active: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User profile retrieved (or created) successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserProfile'];
        };
      };
      /** @description Unauthorized — missing or invalid token. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserRequest'];
      };
    };
    responses: {
      /** @description User profile updated successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserProfile'];
        };
      };
      /** @description Invalid request body. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized — missing or invalid token. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden — insufficient permissions to update this profile. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getNotifications: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of notification types. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NotificationType'][];
        };
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not yet implemented. */
      501: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getUserSubscriptions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of subscriptions. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NotificationSubscription'][];
        };
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not yet implemented. */
      501: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createUserSubscription: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateNotificationSubscriptionRequest'];
      };
    };
    responses: {
      /** @description Subscription created. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NotificationSubscription'];
        };
      };
      /** @description Invalid request. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not yet implemented. */
      501: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteUserSubscription: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Subscription ID. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Subscription deleted. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Subscription not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not yet implemented. */
      501: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateUserSubscription: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Subscription ID. */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateNotificationSubscriptionRequest'];
      };
    };
    responses: {
      /** @description Subscription updated. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NotificationSubscription'];
        };
      };
      /** @description Unauthorized. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Subscription not found. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not yet implemented. */
      501: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
