// One Montréal trip for the journey hero background: a BIXI dock in NDG,
// by bike to Vendôme, Orange line to Berri-UQAM, Yellow line to Longueuil.
// Generated by scripts/preprocess-montreal-journey.mjs from STM GTFS, BIXI
// GBFS and an OSRM bike route; the service alert is fake. Everything here is
// pure (no three.js), so it can be unit-tested.

export type LonLat = [number, number];

export interface JourneyDock {
  name: string;
  point: LonLat;
  capacity: number;
}

export interface JourneyMetroLeg {
  /** GTFS route_id. */
  line: string;
  /** Parent stop_ids. */
  from: string;
  to: string;
  path: LonLat[];
  /** Parent stop_ids along the leg, in travel order. */
  stations: string[];
}

export interface MontrealJourneyData {
  lines: Array<{ id: string; name: string; color: string; path: LonLat[] }>;
  stations: Array<{
    id: string;
    name: string;
    point: LonLat;
    /** GTFS route_ids serving the station. */
    lines: string[];
  }>;
  /** Every BIXI dock around the scene. */
  docks: LonLat[];
  journey: {
    bike: {
      /** `bikesAvailable` is faked to 70% of capacity at build time. */
      from: JourneyDock & { bikesAvailable: number };
      to: JourneyDock;
      distanceM: number;
      path: LonLat[];
    };
    metro: JourneyMetroLeg[];
    alert: { line: string; station: string; point: LonLat };
  };
}

export const JOURNEY_DATA_URL = '/hero-animation/montreal-journey.json';

/**
 * In-flight (or settled) request, so the fetch can be started from module
 * scope — before the scene's chunk has even downloaded — and awaited later.
 */
let pending: Promise<MontrealJourneyData> | null = null;

/**
 * Starts the fetch without waiting for it. Safe to call more than once and
 * on the server, where it does nothing: the URL is relative, and the data is
 * only ever used by the client-only scene.
 */
export function prefetchJourneyData(): void {
  if (typeof window === 'undefined' || pending !== null) return;
  // Plain same-origin defaults, matching the `<link rel="preload" as="fetch">`
  // the home page emits, so the two share one request instead of racing.
  pending = fetch(JOURNEY_DATA_URL)
    .then(async (response) => {
      if (!response.ok) throw new Error('Montréal journey data is missing');
      return (await response.json()) as MontrealJourneyData;
    })
    .catch((error: unknown) => {
      // A failed prefetch must not poison the next attempt.
      pending = null;
      throw error;
    });
}

export async function loadJourneyData(): Promise<MontrealJourneyData> {
  prefetchJourneyData();
  if (pending === null) throw new Error('Montréal journey data is missing');
  return await pending;
}

// ---------------------------------------------------------------------------
// Projection: Web Mercator, so the raster basemap maps linearly onto the
// ground plane. World x is east, world z is south, in units of `kmPerUnit`.
// ---------------------------------------------------------------------------

const EARTH_CIRCUMFERENCE_KM = 40075.016686;

/** Normalized Web Mercator: x, y in [0, 1], y growing southward. */
export function toMercator([lon, lat]: LonLat): [number, number] {
  const phi = (lat * Math.PI) / 180;
  return [
    (lon + 180) / 360,
    (1 - Math.log(Math.tan(phi) + 1 / Math.cos(phi)) / Math.PI) / 2,
  ];
}

export interface Projection {
  /** Mercator position of the world origin. */
  origin: [number, number];
  /** World units per normalized Mercator unit. */
  scale: number;
  toWorld: (point: LonLat) => [number, number];
}

export function createProjection(focus: LonLat, kmPerUnit: number): Projection {
  const origin = toMercator(focus);
  const scale =
    (EARTH_CIRCUMFERENCE_KM * Math.cos((focus[1] * Math.PI) / 180)) / kmPerUnit;
  return {
    origin,
    scale,
    toWorld: (point) => {
      const [x, y] = toMercator(point);
      return [(x - origin[0]) * scale, (y - origin[1]) * scale];
    },
  };
}

export interface TileRange {
  zoom: number;
  minX: number;
  maxX: number;
  minY: number;
  maxY: number;
}

/** Slippy-map tiles covering world [-halfWidth, halfWidth] x [-halfDepth, halfDepth]. */
export function tilesCovering(
  projection: Projection,
  zoom: number,
  halfWidth: number,
  halfDepth: number,
): TileRange {
  const n = 2 ** zoom;
  const toTile = (world: number, axis: 0 | 1): number =>
    Math.floor((projection.origin[axis] + world / projection.scale) * n);
  return {
    zoom,
    minX: toTile(-halfWidth, 0),
    maxX: toTile(halfWidth, 0),
    minY: toTile(-halfDepth, 1),
    maxY: toTile(halfDepth, 1),
  };
}

/** World-space rectangle a tile range covers: [west, north, east, south]. */
export function tileRangeBounds(
  projection: Projection,
  range: TileRange,
): [number, number, number, number] {
  const n = 2 ** range.zoom;
  const x = (tile: number): number =>
    (tile / n - projection.origin[0]) * projection.scale;
  const y = (tile: number): number =>
    (tile / n - projection.origin[1]) * projection.scale;
  return [x(range.minX), y(range.minY), x(range.maxX + 1), y(range.maxY + 1)];
}

// ---------------------------------------------------------------------------
// Polylines in world x/z
// ---------------------------------------------------------------------------

export type Point2 = [number, number];

export interface MeasuredPath {
  points: Point2[];
  /** Distance from the start to each point. */
  distances: number[];
  length: number;
}

export function measurePath(points: Point2[]): MeasuredPath {
  const distances = [0];
  for (let i = 1; i < points.length; i++) {
    const [ax, ay] = points[i - 1];
    const [bx, by] = points[i];
    distances.push(distances[i - 1] + Math.hypot(bx - ax, by - ay));
  }
  return { points, distances, length: distances[distances.length - 1] ?? 0 };
}

/** Point `distance` along the path, clamped to its ends. */
export function pointAlong(path: MeasuredPath, distance: number): Point2 {
  const { points, distances } = path;
  if (points.length === 1 || distance <= 0) return points[0];
  if (distance >= path.length) return points[points.length - 1];
  let i = 1;
  while (distances[i] < distance) i++;
  const t = (distance - distances[i - 1]) / (distances[i] - distances[i - 1]);
  const [ax, ay] = points[i - 1];
  const [bx, by] = points[i];
  return [ax + (bx - ax) * t, ay + (by - ay) * t];
}

/** Distance along the path of its closest point to `point`. */
export function distanceAlong(path: MeasuredPath, point: Point2): number {
  const [px, py] = point;
  let best = Infinity;
  let at = 0;
  for (let i = 1; i < path.points.length; i++) {
    const [ax, ay] = path.points[i - 1];
    const [bx, by] = path.points[i];
    const dx = bx - ax;
    const dy = by - ay;
    const len2 = dx * dx + dy * dy || 1;
    const t = Math.min(
      Math.max(((px - ax) * dx + (py - ay) * dy) / len2, 0),
      1,
    );
    const d = Math.hypot(ax + t * dx - px, ay + t * dy - py);
    if (d < best) {
      best = d;
      at = path.distances[i - 1] + t * Math.sqrt(len2);
    }
  }
  return at;
}

// ---------------------------------------------------------------------------
// Journey timeline
// ---------------------------------------------------------------------------

/** Paths the traveler moves along, in order. */
export type LegId = 'bike' | 'walk' | 'orange' | 'yellow';
export const LEG_IDS: readonly LegId[] = ['bike', 'walk', 'orange', 'yellow'];

export type JourneyPhase =
  | 'riding'
  | 'walking'
  | 'onboard'
  | 'delayed'
  | 'transfer'
  | 'arrived'
  | 'reset';

interface Step {
  leg: LegId;
  /** Start and end distance along the leg; equal for a dwell. */
  from: number;
  to: number;
  seconds: number;
  phase: JourneyPhase;
}

export interface JourneyTimeline {
  steps: Step[];
  duration: number;
  lengths: Record<LegId, number>;
}

export interface JourneyTiming {
  bike: number;
  walk: number;
  /** Orange leg, Vendôme to the alert station. */
  toAlert: number;
  /** Held at the alert station: the "delay". */
  delay: number;
  /** Orange leg, alert station to Berri-UQAM. */
  fromAlert: number;
  transfer: number;
  yellow: number;
  arrived: number;
  /** Traveler and progress fade out before the loop restarts. */
  reset: number;
}

/** About 25 s per loop. */
export const DEFAULT_TIMING: JourneyTiming = {
  bike: 5.8,
  walk: 0.8,
  toAlert: 2.9,
  delay: 1.8,
  fromAlert: 4.4,
  transfer: 0.9,
  yellow: 4.4,
  arrived: 3.0,
  reset: 1.0,
};

export function createTimeline(
  lengths: Record<LegId, number>,
  /** Distance along the orange leg of the alert station. */
  alertAt: number,
  timing: JourneyTiming = DEFAULT_TIMING,
): JourneyTimeline {
  const steps: Step[] = [
    {
      leg: 'bike',
      from: 0,
      to: lengths.bike,
      seconds: timing.bike,
      phase: 'riding',
    },
    {
      leg: 'walk',
      from: 0,
      to: lengths.walk,
      seconds: timing.walk,
      phase: 'walking',
    },
    {
      leg: 'orange',
      from: 0,
      to: alertAt,
      seconds: timing.toAlert,
      phase: 'onboard',
    },
    {
      leg: 'orange',
      from: alertAt,
      to: alertAt,
      seconds: timing.delay,
      phase: 'delayed',
    },
    {
      leg: 'orange',
      from: alertAt,
      to: lengths.orange,
      seconds: timing.fromAlert,
      phase: 'onboard',
    },
    {
      leg: 'yellow',
      from: 0,
      to: 0,
      seconds: timing.transfer,
      phase: 'transfer',
    },
    {
      leg: 'yellow',
      from: 0,
      to: lengths.yellow,
      seconds: timing.yellow,
      phase: 'onboard',
    },
    {
      leg: 'yellow',
      from: lengths.yellow,
      to: lengths.yellow,
      seconds: timing.arrived,
      phase: 'arrived',
    },
    {
      leg: 'yellow',
      from: lengths.yellow,
      to: lengths.yellow,
      seconds: timing.reset,
      phase: 'reset',
    },
  ];
  return {
    steps,
    duration: steps.reduce((sum, s) => sum + s.seconds, 0),
    lengths,
  };
}

export interface JourneyState {
  leg: LegId;
  /** Traveler's distance along `leg`. */
  distance: number;
  phase: JourneyPhase;
  /** 0..1 progress through the current step. */
  stepProgress: number;
  /** Distance covered on every leg (full for past legs, 0 for later ones). */
  traveled: Record<LegId, number>;
  /** Traveler and traveled-path highlight opacity; 0 at the loop seam. */
  presence: number;
}

const easeInOutSine = (x: number): number => -(Math.cos(Math.PI * x) - 1) / 2;

/** Where the traveler is `seconds` into the (looping) journey. */
export function journeyAt(
  timeline: JourneyTimeline,
  seconds: number,
): JourneyState {
  const { steps, duration, lengths } = timeline;
  let t = ((seconds % duration) + duration) % duration;
  let index = 0;
  while (index < steps.length - 1 && t >= steps[index].seconds) {
    t -= steps[index].seconds;
    index++;
  }
  const step = steps[index];
  const stepProgress = Math.min(t / step.seconds, 1);
  const distance =
    step.from + (step.to - step.from) * easeInOutSine(stepProgress);

  const legIndex = LEG_IDS.indexOf(step.leg);
  const traveled = Object.fromEntries(
    LEG_IDS.map((leg, i) => [
      leg,
      i < legIndex ? lengths[leg] : i === legIndex ? distance : 0,
    ]),
  ) as Record<LegId, number>;

  return {
    leg: step.leg,
    distance,
    phase: step.phase,
    stepProgress,
    traveled,
    presence: step.phase === 'reset' ? 1 - stepProgress : 1,
  };
}
